"""new fields in user model

Revision ID: 364831d8abbe
Revises: 330179a69bb5
Create Date: 2020-02-06 16:53:21.292012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364831d8abbe'
down_revision = '330179a69bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
