"""timestamp on task

Revision ID: 9ead40fa4d03
Revises: 3d2bd49b3dd7
Create Date: 2020-04-27 14:26:30.131816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ead40fa4d03'
down_revision = '3d2bd49b3dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_task_timestamp'), 'task', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_timestamp'), table_name='task')
    op.drop_column('task', 'timestamp')
    # ### end Alembic commands ###
